version: 2
jobs:
  build:
    docker:
    - image: deinternetjongens/php7.2
    working_directory: ~/laravel
    steps:
    - checkout
    - run: apt install -y libsqlite3-dev php7.2-bcmath
    - run: composer self-update
    - restore_cache:
        keys:
        - composer-v1-{{ checksum "composer.json" }}
        - composer-v1-
    - run: composer install -n --prefer-dist
    - save_cache:
        key: composer-v1-{{ checksum "composer.json" }}
        paths:
        - vendor
    - run: touch database/testing.sqlite
    - run: php artisan key:generate --env=testing
    - run: php artisan migrate --env=testing --database=sqlite_testing --force
    - run: ./vendor/bin/phpunit
