version: 2
jobs:
  build:
    docker:
    - image: circleci/php:7.2.8-browsers
    working_directory: ~/laravel
    steps:
    - add_ssh_keys:
      fingerprints:
        - "ca:72:1d:d2:cb:fe:ab:03:d8:e5:f2:12:37:e9:35:b4"
    - checkout
    - run: sudo apt-get install -y libsqlite3-dev
    - run: sudo docker-php-ext-install bcmath
    - run: sudo composer self-update
    - restore_cache:
        keys:
        - composer-v1-{{ checksum "composer.json" }}
        - composer-v1-
    - run: composer install -n --prefer-dist
    - save_cache:
        key: composer-v1-{{ checksum "composer.json" }}
        paths:
        - vendor
    - run: touch database/testing.sqlite
    - run: php artisan key:generate --env=testing
    - run: php artisan migrate --env=testing --database=sqlite_testing --force
    - run: ./vendor/bin/phpunit
