version: 2
jobs:
  build:
    docker:
    - image: circleci/php:7.2.8-browsers
    working_directory: ~/laravel
    steps:
    - checkout
    - run: sudo apt-get install -y libsqlite3-dev
    - run: sudo docker-php-ext-install bcmath
    - run: sudo docker-php-ext-install pdo_sqlite
    - run: docker-php-ext-enable pdo_sqlite
    - run: sudo composer self-update
    - restore_cache:
        keys:
        - composer-v1-{{ checksum "composer.json" }}
        - composer-v1-
    - run: composer install -n --prefer-dist
    - save_cache:
        key: composer-v1-{{ checksum "composer.json" }}
        paths:
        - vendor
    - run: touch database/testing.sqlite
    - run: php artisan key:generate --env=testing
    - run: php artisan migrate --env=testing --database=sqlite_testing --force
    - run: ./vendor/bin/phpunit
